### ISSUE TITLE
Prevent unselect

### ISSUE THREAD

**Issue by dylanh724** [jonmiles/bootstrap-treeview#173]
Similar to a radio btn, how can I prevent unselect?

**Comment by zakkojo** [comment]
I'm interested in it too!! 
In my tree one node must always be selected, is there any way to achieve it?!?

**Comment by jkshay** [comment]
I too am in need of this feature.  One node must always be selected.

**Comment by jkshay** [comment]
I was able to give my treeview the behavior I wanted.  Here's how I did it:

The treeview, when NOT in multiSelect mode, raises the nodeUnselected event under two conditions:

1. A node is currently selected, and a new unselected node is selected (which raises the nodeUnselected event, followed by the nodeSelected event), OR
2. A currently selected node is clicked (which simply raises the nodeUnselected event)

The problem I had with getting the desired behavior is in the 2nd case listed above.  When handling the nodeUnselected event, I didn't have any way to know if the event was raised because a user "de-selected" a node or simply clicked on a new node.

I noticed that the treeview, when it IS in multiSelect mode, does not raise the nodeUnselected event in the 1st case listed above.  However, it DOES raise the nodeUnselected event when the user actually clicks on the already-selected node.

So, while I really DON'T want multiSelect behavior, I take advantage of this behavior (along with the ability to suppress events) to get to my goal.

In a nutshell, I have a nodeSelectHandler function and a nodeUnselectHandler function.

My treeview declaration is as such:
`$('#tree').treeview({
        data: JSON.stringify(@Html.Raw(Json.Encode(@OptionsVM.Tree.nodes.ToArray()))),
        onNodeSelected: nodeSelectHandler,
        onNodeExpanded: resizeTreePanel,
        onNodeCollapsed: resizeTreePanel,
        collapseIcon: "fa fa-chevron-down",
        expandIcon: "fa fa-chevron-right",
        emptyIcon: "fa",
        showBorder: false,
        onhoverColor: "#d9d9d9",
        multiSelect: true,
        onNodeUnselected: nodeUnselectHandler
    });`

Note my assigned event handlers for onNodeSelected and onNodeUnselected.  Also note the option multiSelect is true.

Then, in my nodeUnselectHandler, I simply select the node but suppress the nodeSelected event:
`function nodeUnselectHandler(event, data) {
        var node = $("#tree").treeview('getNode', data.nodeId);
        $("#tree").treeview('selectNode', [node, { silent: true }]);
    }`

And in my nodeSelectHandler, I simply unselect every selected node that isn't the current target (and suppress the nodeUnselected event):

`function loadPage(event, data) {
        
        var selectedNodes = $("#tree").treeview('getSelected');
        $(selectedNodes).each(function (index, element) {
            if (element.nodeId !== data.nodeId) {
                $("#tree").treeview('unselectNode', [element, { silent: true }]);
            }
        });
        insert remainder of your custom select handling code here...
}`

This gives me exactly the behavior I am seeking.  A single node is always selected - even if the user tries to "unselect" the currently selected node.  I hope others might find this useful.
