### ISSUE TITLE
Search Tag or Badge

### ISSUE THREAD

**Issue by bijuva** [jonmiles/bootstrap-treeview#218]
Hi @jonmiles,
Is there a way to search for nodes that has a tag? Or any work around to loop through nodes and expand nodes that has a tag? TIA...

Biju

**Comment by wunc** [comment]
The built-in search function searches the `text` field. If you have control over the generation of the data, you can add an element to that field that won't display, but will still be searchable. So, instead of

```
text: "Item",
```

you could use

```
text: "Item<span data-tags='tag1,tag2' data-has-tags></span>",
```
So then, if you search for `has-tags`, every item with that `data-has-tags` attribute will be in the results. If you don't have control over the generation of the data, you could parse the data object and append this info to the text before initializing treeview.

**Comment by jonmiles** [comment]
Sorry but I'm not going to add a search on tags / badges.

However, v2.0 will provide full support for searching all node properties; currently you can only query 'text'.  Therefore, the proposed solution would be to add a key value pair to your node data.  Then use new `findNodes()` method to query nodes by your custom values.

If you want to access pre-release v2.0, please checkout `develop` branch and be sure to review README for breaking changes.  Hope this helps.
