### ISSUE TITLE
Expand / collapse nodes programatically

### ISSUE THREAD

**Issue by Cyruxx** [jonmiles/bootstrap-treeview#28]
Please add more methods like: expand all, collapse all, collapse X, expand X...

**Comment by phax** [comment]
These methods are really needed!!

**Comment by jonmiles** [comment]
Proposed methods, to be confirmed

* expandNode(id)
* expandAll(level)
* collapseNode(id)
* collapseAll(level)

**level** - would allow expanding and collapsing to a certain tree level

**Comment by phax** [comment]
if "level" would be "-1" would it mean "all levels"?
Alternatively you could use "expandTo(level)" and "collapseTo(level)" and an additional "expandAll()" and "collapseAll()".

**Comment by jonmiles** [comment]
I had thought of having expandTo(level) as well but my intention (admittedly unclear in previous comment) was to make level optional.  If level was omitted then it would expand to all levels, or alternatively you could provide level = 99.

I'm also toying with the idea of adding the optional level argument to expand and collapse node methods; to provide more fine-grained control.

**Comment by phax** [comment]
Please don't limit levels to 99 and make 99 a special number - you never know how people are using it. Either omit the parameter for "all" or use -1 as negative values are forbidden by semantics.
Could you please elaborate on the idea on adding a level argument to expand and collapse - I don't know what you're aiming towards...

**Comment by jonmiles** [comment]
I didn't say 99 would be a special number or a limit, just like I didn't suggest -1.  It was merely an example that you could expand to n levels, to effectively expand all levels.

Using level in expand and collapse nodes allows you to expand/collapse any given node of the tree by n levels.  Essentially expanding a single branch rather than the entire tree.  The default would be 1 level, so if omitted it would act as expected and only open the immediate node.

**Comment by phax** [comment]
Okay, got your point. But having some possibility to really collapse all (either with a special method or with a constant) might be helpful - both for the user and for implementation since no level determination and/or recursion needs to be done.

I now get your idea on expand and collapse on any given node. So it is a "relative" expansion from the current node. I think this is a very good idea.
