### ISSUE TITLE
Can programmatically put the tree in some state when setup?

### ISSUE THREAD

**Issue by boriscougar** [jonmiles/bootstrap-treeview#43]
Hi, I want to put the tree in some state when the page loads, for example, open up the first parent node and its child and set the selected node the grandson like:

 (When page loads)
- Parent
   - Child
       - Grandson<selected
+ Parent2
+ Parent3

**Comment by jonmiles** [comment]
The current implementation only allows you to set the initial levels that the tree will render as open/expanded on initialisation.  

The project started out as an example of what could quickly and easily be done using bootstrap's existing components, and wasn't originally intended to be a feature rich tree view to cover all potential use cases.  However, due to its popularity and ongoing requests I do now intend to add a comprehensive range of features; including the ability to setup initial state and programmatic node selection.

I will be setting aside a small amount of time each week to work through feature enhancements.  Keep an eye on the project repository for future updates.

**Comment by boriscougar** [comment]
I came up with a method to implement what i want using _nodes and nodes on
underlying tree and then calling _render. I guess the same effect could be
achieved by a new attribute while traversing the tree and choosing weather
or not to show up that tree branch. Anyway I'm not so javascript fluent but
I'll try to contribute somehow.

Thanks for your plugin :)

**Comment by jonmiles** [comment]
FYI I've raised #49 to cover your requirements

**Comment by jonmiles** [comment]
@boriscougar I have implemented definable node states, coincidentally it was one of the first things I had to work on.  If you want to check it out ahead of the pending v1.1.0 release, you can checkout the `develop` branch.

Your scenario would be achieved with the following data structure.

```javascript
[
  {
    text: 'Parent 1',
    states: {
      expanded: true
    },
    nodes: [
      {
        text: 'Child 1',
        states: {
          expanded: true
        },
        nodes: [
          {
            text: 'Grandchild 1',
            states: {
              selected: true
            }
          }
        ]
      },
      {
        text: 'Child 2',
        href: '#child2'
      }
    ]
  },
  {
    text: 'Parent 2'
  },
  {
    text: 'Parent 3'
  }
]
```

Please refer to #49 and the updated README.md for full details.
