### ISSUE TITLE
enableLinks and href

### ISSUE THREAD

**Issue by mxmissile** [jonmiles/bootstrap-treeview#57]
I have `enableLinks` set to true, and am setting the `href` property `#1213` for example. Clicking around on my tree, the url in the browser's address box changes according and correctly.

However, if I use that same url (including the hash) in a new tab, it does not show the current node as selected. Am I missing something? Or is this not what the enableLinks/href properties are for?

**Comment by jonmiles** [comment]
That's not how anchor tags work, nor is it how the tree view is designed to work.  Enabling links and setting a href simply makes the tree node's text act as a hyperlink.

In order to achieve what you describe, you would need to intercept/detect the URL change and then update the tree's state.  Although it's not possible in the current release, as you can't define initial states.  This has been implemented recently (see #49) and will be available in the next release; v1.1.0.

Depending on what you want to achieve with your implementation, I would suggesting using the nodeSelected event is a better approach than hyperlinks.

**Comment by mxmissile** [comment]
Gotcha, thanks for the clarification.
