### ISSUE TITLE
Avoid recreating the DOM (of the treeview) on state changes?

### ISSUE THREAD

**Issue by aauthor** [jonmiles/bootstrap-treeview#76]
First of all, excellent plugin, great documentation, and great code!

An issue that I ran into in one of my projects where I had a fairly large tree (60 elements) was that using `search` on an input event (i.e. every keystroke) caused noticeable lag.  When I dug into the code, I found the culprit to be the two calls in `search` to `render` (one via `clearSearch`).  The slow down is due to the `render` method destroying and recreating the entire DOM of the treeview.  I make [a small patch](https://github.com/aauthor/bootstrap-treeview/commit/7d4a38d1b124361853cea17784516f5109dcd7de) to allow you to access both the node object from its `<li>` DOM element and visa-versa, and then in the `search` and `clearSearch` modifying the class of the node object's `<li>` element (removing the call to `render`.

While I haven't bench-marked it, this change made the search function happen with no noticeable lag.  I noticed a similar enhancement issue that you've opened in #44.  What do you think of this approach, and would you be open to a PR in which I implemented this across all the events that cause a re-render?

**Comment by jonmiles** [comment]
Thanks for bringing this to my attention.  I realize now I haven't actually test the search functionality with a really large tree.

I am aware that it re-renders the entire tree on every update.  This is one reason why I've been experimenting with React.js (https://github.com/jonmiles/react-bootstrap-treeview), also as you stated I have some related issues and intend to investigate alternative approaches in the near future.

As for your suggestion.  I think it's a good idea, and should definitely prove beneficial in your scenario.  However, it would only work with the current (v1.1.0) `search`, one of the new updates is the `revealResults` option which as it stands would require re-rendering the tree to expand the parents.  Again it would work with `selected` but only in v1.1.0, as another new feature is the selectedIcon option, which would require a re-render.

That said as we move forward into v1.3.0 and implement #50 and #47, which I plan to start very soon.  This may well be part of a hybrid approach that I take.  As a bit of background, I intend to break down the render method so individual nodes with a dirty state can be rendered instead of the whole tree.  Once it's possible to re-render individual nodes, then to implement #47 I intend to render the entire tree and use classes to show/hide (display:none) individual nodes (similar to the React approach).  I guess this is the same approach as you're suggesting with adding/removing search-result classes.

I think I will put in a suppress render option into v1.2.0 to stop the `clearSearch` from rendering unnecessarily when search is being called.  Just to get this next release finished and out the door.  Then look to completely address these performance issues in v1.3.0, as discussed above.

**Comment by aauthor** [comment]
Great!  Best of luck to you, and if I can be of any assistance, let me know.

**Comment by kshchepanovskyi** [comment]
Good to know that you are improving performance :) I'm using bootstrap-treeview with relatively big tree (currently - few hundred nodes, in future - up to few thousand), so performance is critical. I would be happy to help you with testing, if needed.

**Comment by jonmiles** [comment]
@kshchepanovskyi Thanks, it's encouraging to know people are not only finding this project useful but using in such scale.  Actually I have very nearly finished this change, I just have one little issue related to `_newNodeEl` and `revealResults` which needs some further consideration and testing.  I'm currently swamped with work and the school holidays, so if you want to help with testing that would be great.  You'll need to checkout branch `feature/76-avoid-dom-recreation`.

@aauthor Might be worth your while checking out the updates, see if you can spot anything I've missed.
