### ISSUE TITLE
Where's the multiSelect?

### ISSUE THREAD

**Issue by palenshus** [jonmiles/bootstrap-treeview#91]
Am I crazy or is multiSelect not at all implemented? I added the multiSelect: true as directed in my tree config, and after it didn't work, looked at the code and could find no reference to multiSelect.

**Comment by jonmiles** [comment]
Set `multiSelect = true`, click one node and then click another node, result being that both are selected.

This is the default behaviour of the code ever since the node states implementation.  The option multiSelect was added to revert the change in behaviour.

The only implementation necessary can be found in `setSelectedState`.  When set to false, it remove any previous selections.
