### ISSUE TITLE
an node that contains an empty array of nodes displays expansion icon (+) but should not

### ISSUE THREAD

**Issue by ebengtso** [jonmiles/bootstrap-treeview#96]
The root element has no child but the expansion icon is displayed.
{text:'root',nodes:[]}

**Comment by jonmiles** [comment]
Good spot.  This seems to have crept back in during recent changes.

**Comment by tefotazo** [comment]
Line 530 (approximately) change if state for: if (node.nodes != undefined && node.nodes.length > 0) { ... }

**Comment by reinaris** [comment]
https://github.com/jonmiles/bootstrap-treeview/pull/136

**Comment by jonmiles** [comment]
A better way would be to parse the data on initialization, otherwise you end up with nasty looking if conditions. The check node.nodes is also used in many other places which could result in other such unpredictable behaviour.

I've fixed this in the latest development branch, will be part of 2.0 release.
